#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP_DIR="${ROOT_DIR}/.tmp"
BACK_REPO_DIR="${TMP_DIR}/repo-back"

BACK_REPO="${BACK_REPO:-ORG/repo-back}"
BACK_BRANCH="${BACK_BRANCH:-main}"
BACK_REPO_URL="${BACK_REPO_URL:-https://github.com/${BACK_REPO}.git}"
BACK_REPO_TOKEN="${BACK_REPO_TOKEN:-${GH_PAT:-}}"

OUT_DIR="${ROOT_DIR}/openapi"
OUT_FILE="${OUT_DIR}/backend.json"
STATIC_OUT_DIR="${ROOT_DIR}/static/openapi"
STATIC_OUT_FILE="${STATIC_OUT_DIR}/backend.json"

mkdir -p "${TMP_DIR}" "${OUT_DIR}" "${STATIC_OUT_DIR}"

rm -rf "${BACK_REPO_DIR}"
if [[ -n "${BACK_REPO_TOKEN}" ]]; then
  BACK_REPO_URL="https://x-access-token:${BACK_REPO_TOKEN}@github.com/${BACK_REPO}.git"
fi

echo "Cloning back repo: ${BACK_REPO} (${BACK_BRANCH})"
git clone --depth 1 --branch "${BACK_BRANCH}" "${BACK_REPO_URL}" "${BACK_REPO_DIR}"

if [[ ! -f "${BACK_REPO_DIR}/scripts/export_openapi.py" ]]; then
  echo "ERROR: export script not found at scripts/export_openapi.py in back repo."
  exit 1
fi

echo "Generating OpenAPI spec via backend script"
(cd "${BACK_REPO_DIR}" && python3 scripts/export_openapi.py)

if [[ ! -f "${BACK_REPO_DIR}/openapi.json" ]]; then
  echo "ERROR: openapi.json not generated by backend script."
  exit 1
fi

cp "${BACK_REPO_DIR}/openapi.json" "${OUT_FILE}"

if [[ ! -s "${OUT_FILE}" ]]; then
  echo "ERROR: OpenAPI output is missing or empty: ${OUT_FILE}"
  exit 1
fi

cp "${OUT_FILE}" "${STATIC_OUT_FILE}"

echo "OpenAPI spec ready at ${OUT_FILE}"
